/****************************************************
 * Executable:  Single_list_driver
 * Author:  Douglas Wilhelm Harder
 * Copyright (c) 2006-13 by Douglas Wilhelm Harder.  All rights reserved.
 *
 * DO NOT EDIT THIS FILE
 *
 * Create an instance of the Single_list_tester<Type> class
 * and call the member function run().
 *
 * The two options for Type are 'int' and 'double', and the appropriate
 * tester is selected by passing the type at the command line.  If the
 * name of the executable is a.out on ecelinux, the correct calling
 * sequence to test the default test files is:
 *
 *  $ ./a.out int < int.in
 *  $ ./a.out double < double.in
 *
 * The member function run() will interpret the
 * input appropriately and exit when the interpreter
 * receives either the command 'exit' or and
 * end-of-file.
 ****************************************************/

#include <iostream>
#include <string>
#include <cstring>
#include "Single_list_tester.h"

int main( int argc, char *argv[] ) {
	if ( argc != 2 ) {
		std::cerr << "Expecting a command-line argument" << std::endl;

		return -1;
	}

	std::cout << "Starting Test Run" << std::endl;

	if ( !std::strcmp( argv[1], "int" ) ) {
		Single_list_tester<int> tester;

		tester.run();
	} else if ( !std::strcmp( argv[1], "double" ) ) {
		Single_list_tester<double> tester;

		tester.run();
	} else {
		std::cerr << "Expecting a command-line argument of either 'int' or 'double', but got '" << argv[1] << "'" << std::endl;

		return -1;
	}

	std::cout << "Finishing Test Run" << std::endl;

	return 0;
}
